services:
  config-server:
    image: config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - configs_net

  discovery-server:
    image: discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - configs_net

  associations_db_ms:
    container_name: associations_db
    image: postgres
    environment:
      POSTGRES_USER: ${associations_db_user}
      POSTGRES_PASSWORD: ${associations_db_password}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - associations_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - associations_net

networks:
  configs_net:
    driver: bridge
  associations_net:
    driver: bridge

volumes:
  associations_data: