services:
  config-server:
    image: config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - configs-network

  discovery-server:
    image: discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - configs-network

networks:
  configs-network:
    driver: bridge
